title: My Personal Website
description: >-
  I'm a PhD student in genomic bioinformatics at the University of Rennes, France.
  I'm passionate about FAIR and Open Science, and I'm a strong advocate for the use of
  open-source software in research.
url: "https://louislenezet.github.io"
github_username:  LouisLeNezet

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
