title: Louis Le Nézet
url: "https://louislenezet.github.io"
github_username:  LouisLeNezet

words_per_minute: 275

# Build settings
paginate: 4
paginate_path: "/page/:num"

permalink: pretty
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

  - scope:
      path: '_posts'
    values:
      permalink: /:year/:month/:day/:title/
  - scope:
      path: '_posters'
    values:
      permalink: /posters/:title/

include:
  - "_pages"
  - "assets/"

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - environment.yml
  - .wordlist.txt
  - .spellcheck.yml

sass:
  sass_dir: _sass
  style: compressed
