name: env_website
channels:
  - conda-forge
  - defaults
dependencies:
  - gcc
  - gxx_linux-64
  - conda-forge::ruby>=3.4
  - conda-forge::libffi
  - conda-forge::pdf2image
  - conda-forge::cffconvert
  - conda-forge::pyyaml
  - conda-forge::pybtex
